### ISSUE TITLE
alias .ready with .r

### ISSUE THREAD

**Issue by StyrofoamDracula** [Martig3/csgo-discord-scrimbot#15]
As a devops engineer, I want to do my part to improve the user experience. 

Players naturally attempt .r when attempting to "ready-up" as a match ends the Pick phase.
Alias ".ready" with ".r" to simplify the user experience.

Additionally, consider ".j" for ".join" for extra simplicity.

![image](https://user-images.githubusercontent.com/54244226/119916123-ec147b00-bf31-11eb-81b6-711ab49a9273.png)
![image](https://user-images.githubusercontent.com/54244226/119916130-f20a5c00-bf31-11eb-875d-b53cc98aadc5.png)

**Comment by martig3** [comment]
thanks for the feedback, version 0.17.0 will contain this feature
