### ISSUE TITLE
Add multiple inline commands option. 

### ISSUE THREAD

**Issue by StyrofoamDracula** [Martig3/csgo-discord-scrimbot#25]
Add multiple inline commands option. 

Example:
2 players are afk and an admin wants to kick them from the queue.
.kick @user1 @user2 "feel free to rejoin if you guys come back"

The .recoverqueue command has a similar functionality where you can list multiple individuals already.

**Comment by martig3** [comment]
might be also worth it to DM users if they get kicked with a comment

**Comment by StyrofoamDracula** [comment]
I think that because they already get hit with @'s in the message, it would be overwhelming
